### ISSUE TITLE
PostgreSQL backend connection leak

### ISSUE THREAD

**Issue by karlsoon** [cavaliercoder/libzbxpgsql#20] opened 2015-10-14 10:07 UTC
Hi!
I installed from trunk ang get high number of postgress proccesses.
After restart zabbix all was ok, but now its grow.
![zabbix1](https://cloud.githubusercontent.com/assets/3785740/10480736/548571da-7285-11e5-951c-e1cd5b9adf0e.png)

**Comment by cavaliercoder** [comment] 2015-10-14 11:58
Duplicate of #16 fixed in v0.2.1.

If you are using >0.2.1 version and the problem persists, please reopen the issue and provide the following:
* Where you installed from (tar ball, rpm, git, etc.)
* The last query on each of the leaked connections `select query from pg_stat_activity;`

**Comment by karlsoon** [comment] 2015-10-15 08:56
I use git master.
Before this reply i used updated version by 'git pull' from old release.
But after start this issue, i removed .so from /usr/local/lib, stop zabbix-agent, do git clone and build .so again. After start of zabbix-agent there is grow again.
Cannot attach requested info, so, please see it at http://pastebin.com/yR851Sy5

--
Just to clarify: i get mistake.
Trunk is analog of master branch in SVN terminology.

**Comment by cavaliercoder** [comment] 2015-10-16 00:21
Thanks, that's perfect. It looks like it's leaking the same connection I fixed in v0.2.1 so I'm a little confused, but we'll take a close look.

Apologies as I should have asked before, can you please provide the following:
* Zabbix server version
* Zabbix agent version
* PostgreSQL server version
* PostgreSQL libs version used by agent module
* Result of `zabbix_get -s 127.0.0.1 -k pg.modver`

**Comment by karlsoon** [comment] 2015-10-16 06:06
Zabbix server is 2.4.5(also on postgresql DB, but monitoring for another server. i do not monitor PGsql on zabbix server);
Zabbix agent is 2.4.5;
PostgreSQL server - 9.4.4
PostgreSQL libs - i think is the same version. How to check it?
On `zabbix_get -s 127.0.0.1 -k pg.modver` on server that monitored - nothing returned.
But if i run `zabbix_get -s 10.48.107.12 -k pg.modver` from zabbix server, there is:
libzbxpgsql 0.2.1

**Comment by cavaliercoder** [comment] 2015-10-21 14:08
The last query on most of the backends in your pastebin appears to be for items `pg.index.discovery` and `pg.table.discovery`, both of which use the new 'wide' discovery feature by calling `pg_get_discovery_wide()`. I suspect this may be the issue but there is no obvious leak. I'll dig in a little further and advise.

Are you explicitly using the `shallow` parameters for those discovery items or just the default `deep` mode?

**Comment by cavaliercoder** [comment] 2015-10-21 14:55
Should be fixed in 140f060. Please test and advise :)

**Comment by karlsoon** [comment] 2015-10-22 08:28
i dont know what it is mean:
"Are you explicitly using the  shallow  parameters for those discovery items or just the default  deep  mode?"
Anyway, i will update again to master, build it and test.

**Comment by cavaliercoder** [comment] 2015-10-22 08:32
It's not documented yet, but you can specify 'shallow' discovery for index and table discoveries. This causes the agent to only discover items on the current connected database. If you use the 'deep' discovery (the new default), the agent will discover items in *all* connectable databases on the database server. If you haven't specified it will be defaulting to deep discovery which is where I found a connection leak.

**Comment by karlsoon** [comment] 2015-10-22 11:30
I do not change any behavior.
Also, i think the problem is gone with current master branch.
![new-pgsql](https://cloud.githubusercontent.com/assets/3785740/10664142/2dd5f4d2-78da-11e5-9074-2b8d7dafdc18.PNG)

**Comment by cavaliercoder** [comment] 2015-10-22 13:21
Excellent thank you!

**Closed by cavaliercoder** 2015-10-22 13:21 UTC
Labels: bug
