### ISSUE TITLE
Error compiling sources v1.0

### ISSUE THREAD

**Issue by dapi** [cavaliercoder/libzbxpgsql#68] opened 2016-11-29 21:06 UTC
```
bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -I/root/zabbix-3.2.1/include -I/usr/include/postgresql -L/usr/lib/x86_64-linux-gnu -lpq -g -O2 -MT libzbxpgsql_la-pg_bgwriter.lo -MD -MP -MF .deps/libzbxpgsql_la-pg_bgwriter.Tpo -c -o libzbxpgsql_la-pg_bgwriter.lo `test -f 'pg_bgwriter.c' || echo './'`pg_bgwriter.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/root/zabbix-3.2.1/include -I/usr/include/postgresql -L/usr/lib/x86_64-linux-gnu -lpq -g -O2 -MT libzbxpgsql_la-pg_bgwriter.lo -MD -MP -MF .deps/libzbxpgsql_la-pg_bgwriter.Tpo -c pg_bgwriter.c  -fPIC -DPIC -o .libs/libzbxpgsql_la-pg_bgwriter.o
In file included from /root/zabbix-3.2.1/include/module.h:23:0,
                 from libzbxpgsql.h:32,
                 from pg_bgwriter.c:20:
pg_bgwriter.c: In function ‘PG_STAT_BGWRITER’:
pg_bgwriter.c:49:40: error: expected ‘)’ before ‘pgsql_bgwriter_stat’
     zbx_snprintf(query, sizeof(query), pgsql_bgwriter_stat, field);
                                        ^
/root/zabbix-3.2.1/include/zbxtypes.h:162:33: note: in definition of macro ‘ZBX_CONST_STRING’
 #define ZBX_CONST_STRING(str) ""str
                                 ^
pg_bgwriter.c:49:5: note: in expansion of macro ‘zbx_snprintf’
     zbx_snprintf(query, sizeof(query), pgsql_bgwriter_stat, field);
     ^
pg_bgwriter.c: In function ‘PG_BG_TIME_RATIO’:
pg_bgwriter.c:167:40: error: expected ‘)’ before ‘pgsql_bg_time_ratio’
     zbx_snprintf(query, sizeof(query), pgsql_bg_time_ratio, field);
                                        ^
/root/zabbix-3.2.1/include/zbxtypes.h:162:33: note: in definition of macro ‘ZBX_CONST_STRING’
 #define ZBX_CONST_STRING(str) ""str
                                 ^
pg_bgwriter.c:167:5: note: in expansion of macro ‘zbx_snprintf’
     zbx_snprintf(query, sizeof(query), pgsql_bg_time_ratio, field);
     ^
make[2]: *** [libzbxpgsql_la-pg_bgwriter.lo] Error 1
make[2]: Leaving directory `/root/libzbxpgsql-1.0.0/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/libzbxpgsql-1.0.0'
make: *** [all] Error 2

```

**Comment by BusinessTec** [comment] 2016-12-09 19:07
Run into the same error with Zabbix source 3.2.1 - any solution?

**Comment by ilgizar** [comment] 2016-12-21 05:10
The error is relevant to Zabbix source 3.2.2.

**Comment by cavaliercoder** [comment] 2016-12-27 01:41
Hi team, thanks for posting all this info and for your patience.

Unfortunately I haven't been able to replicate this issue with Debian or CentOS, with Zabbix 3.2.1 or 3.2.2. I've also tried using using the v1.0.0 tarball, v1.0.0 git tag and the master branch but I simply can't reproduce the error.

The only clue I can see is that it seems to be an issue expanding the `zbx_snprintf` macro.
Please respond with the following:

* What version of Zabbix source and where you got it from
* Ensure that the Zabbix sources themselves can build
* What version of libzbxpgsql sources and where you got it from
* Operating system release details and compiler details
* Full error log if compilation fails

**Comment by cavaliercoder** [comment] 2017-02-20 13:20
@ilgizar Can you please elaborate on the fix you made? I still haven't been able to understand or replicate this issue.

**Comment by mcourtois** [comment] 2017-03-07 16:49
I just ran into the same issue with Zabbix 3.2.4 on Ubuntu 16.04. I got the Zabbix sources directly from the Zabbix website and I made sure Zabbix compiles OK. I got libzbxpgsql sources directly from Github and I tried compiling with a checkout of the tag v1.1.0 and master but got the same result:


[build-log.txt](https://github.com/cavaliercoder/libzbxpgsql/files/825118/build-log.txt)

**Comment by johusta** [comment] 2017-03-07 17:17
Hi there I just ran into this issue as well:
zabbix source zabbix-3.0.6 (from tar)
ubuntu 16.04.2
libzbxpgsql-1.1.0 - from tar as well
platform s390x


In file included from /opt/zabbix/zabbix-3.0.6/include/module.h:23:0,
                 from libzbxpgsql.h:45,
                 from pg_bgwriter.c:20:
pg_bgwriter.c: In function 'PG_STAT_BGWRITER':
pg_bgwriter.c:49:40: error: expected ')' before 'pgsql_bgwriter_stat'
     zbx_snprintf(query, sizeof(query), pgsql_bgwriter_stat, field);
                                        ^
/opt/zabbix/zabbix-3.0.6/include/zbxtypes.h:162:33: note: in definition of macro 'Z   BX_CONST_STRING'
 #define ZBX_CONST_STRING(str) ""str
                                 ^
pg_bgwriter.c:49:5: note: in expansion of macro 'zbx_snprintf'
     zbx_snprintf(query, sizeof(query), pgsql_bgwriter_stat, field);
     ^
pg_bgwriter.c: In function 'PG_BG_TIME_RATIO':
pg_bgwriter.c:167:40: error: expected ')' before 'pgsql_bg_time_ratio'
     zbx_snprintf(query, sizeof(query), pgsql_bg_time_ratio, field);
                                        ^
/opt/zabbix/zabbix-3.0.6/include/zbxtypes.h:162:33: note: in definition of macro 'Z   BX_CONST_STRING'
 #define ZBX_CONST_STRING(str) ""str
                                 ^
pg_bgwriter.c:167:5: note: in expansion of macro 'zbx_snprintf'
     zbx_snprintf(query, sizeof(query), pgsql_bg_time_ratio, field);
     ^
Makefile:506: recipe for target 'libzbxpgsql_la-pg_bgwriter.lo' failed
make[2]: *** [libzbxpgsql_la-pg_bgwriter.lo] Error 1
make[2]: Leaving directory '/opt/libzbxpgsql/libzbxpgsql-1.1.0/src'
Makefile:399: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/libzbxpgsql/libzbxpgsql-1.1.0'
Makefile:330: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by johusta** [comment] 2017-03-07 17:58
I substituted the pgsql_bg_time_ratio and pgsql_bgwriter_stat with their respective values as ilgizar suggested and make completed.

**Comment by Atem18** [comment] 2017-04-26 15:01
I did not understood what need to be done. Is it possible to provide a patch ? Thanks in advance.

**Comment by cavaliercoder** [comment] 2017-05-05 15:33
Please note that the master branch of this GitHub repo is *not* a stable branch. To build from source, please download the provided distro tarballs, or checkout a tag stable release of this repo before trying to build.

**Comment by Atem18** [comment] 2017-05-09 07:47
@cavaliercoder I did just as you said, I downloaded your official tarball : http://cdn.cavaliercoder.com/libzbxpgsql/libzbxpgsql-1.1.0.tar.gz and followed your compile procedure:
```
./configure --with-zabbix=/usr/src/zabbix
make
make install
```

And there is still the same error:
```
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/src/zabbix-3.2.5/include -I/usr/include/postgresql -L/usr/lib/x86_64-linux-gnu -lpq -g -O2 -MT libzbxpgsql_la-pg_bgwriter.lo -MD -MP -MF .deps/libzbxpgsql_la-pg_bgwriter.Tpo -c -o libzbxpgsql_la-pg_bgwriter.lo `test -f 'pg_bgwriter.c' || echo './'`pg_bgwriter.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/src/zabbix-3.2.5/include -I/usr/include/postgresql -L/usr/lib/x86_64-linux-gnu -lpq -g -O2 -MT libzbxpgsql_la-pg_bgwriter.lo -MD -MP -MF .deps/libzbxpgsql_la-pg_bgwriter.Tpo -c pg_bgwriter.c  -fPIC -DPIC -o .libs/libzbxpgsql_la-pg_bgwriter.o
In file included from /usr/src/zabbix-3.2.5/include/module.h:23:0,
                 from libzbxpgsql.h:45,
                 from pg_bgwriter.c:20:
pg_bgwriter.c: In function 'PG_STAT_BGWRITER':
pg_bgwriter.c:49:40: error: expected ')' before 'pgsql_bgwriter_stat'
     zbx_snprintf(query, sizeof(query), pgsql_bgwriter_stat, field);
                                        ^
/usr/src/zabbix-3.2.5/include/zbxtypes.h:162:33: note: in definition of macro 'ZBX_CONST_STRING'
 #define ZBX_CONST_STRING(str) ""str
                                 ^
pg_bgwriter.c:49:5: note: in expansion of macro 'zbx_snprintf'
     zbx_snprintf(query, sizeof(query), pgsql_bgwriter_stat, field);
     ^
pg_bgwriter.c: In function 'PG_BG_TIME_RATIO':
pg_bgwriter.c:167:40: error: expected ')' before 'pgsql_bg_time_ratio'
     zbx_snprintf(query, sizeof(query), pgsql_bg_time_ratio, field);
                                        ^
/usr/src/zabbix-3.2.5/include/zbxtypes.h:162:33: note: in definition of macro 'ZBX_CONST_STRING'
 #define ZBX_CONST_STRING(str) ""str
                                 ^
pg_bgwriter.c:167:5: note: in expansion of macro 'zbx_snprintf'
     zbx_snprintf(query, sizeof(query), pgsql_bg_time_ratio, field);
     ^
make[2]: *** [libzbxpgsql_la-pg_bgwriter.lo] Error 1
Makefile:506: recipe for target 'libzbxpgsql_la-pg_bgwriter.lo' failed
make[2]: Leaving directory '/usr/src/libzbxpgsql-1.1.0/src'
Makefile:399: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/usr/src/libzbxpgsql-1.1.0'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Could you fix it please ?

**Comment by cavaliercoder** [comment] 2017-05-09 09:13
I still am unable to replicate this issue.

I notice @johusta is compiling on Z series architecture. What architecture is everyone else compiling on (@dapi, @BusinessTec, @Atem18, @ilgizar, @mcourtois). I have only tested on i386 and x86_64. 

Knowing this is an issue with the expansion of the 'zbx_snprintf` macro in the Zabbix sources, it might be related to differences in the underlying data types for non x86 platforms. Just a hunch.

**Comment by Atem18** [comment] 2017-05-09 10:05
@cavaliercoder I am building it inside a docker container running Debian Jessie 8.8 on x86_64 and Zabbix 3.2.5:
```
Linux KEVINM 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux
```
```
root@HOSTNAME:/usr/src# ls
libzbxpgsql-1.1.0  zabbix-3.2.5
```

Here is my Dockerfile for reference:
```
FROM debian:jessie

RUN apt-get update && apt-get install -y --no-install-recommends libconfig-dev libpq-dev automake build-essential libtool curl mysql-client php5-mongo php5-cli patch libffi-dev supervisor cron gcc make libgnutls28-dev python-setuptools libpython2.7-dev libssl-dev libwww-perl libmongodb-perl jq wget python-apt openssh-client git vim && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get clean

ARG ZBX_VERSION=3.2.5
ARG LIBZBXPGSQL_VERSION=1.1.0
WORKDIR /usr/src
ADD http://ufpr.dl.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/${ZBX_VERSION}/zabbix-${ZBX_VERSION}.tar.gz /usr/src/zabbix.tar.gz
ADD https://raw.githubusercontent.com/gmichels/docker-zabbix-agent/master/patches/fs_discovery.patch /usr/src/zabbix-$ZBX_VERSION/fs_discovery.patch
ADD https://raw.githubusercontent.com/monitoringartist/zabbix-docker-monitoring/master/src/modules/zabbix_module_docker/Makefile /usr/src/zabbix-$ZBX_VERSION/src/modules/zabbix_module_docker/Makefile
ADD https://raw.githubusercontent.com/monitoringartist/zabbix-docker-monitoring/master/src/modules/zabbix_module_docker/zabbix_module_docker.c /usr/src/zabbix-$ZBX_VERSION/src/modules/zabbix_module_docker/zabbix_module_docker.c
ADD http://cdn.cavaliercoder.com/libzbxpgsql/libzbxpgsql-$LIBZBXPGSQL_VERSION.tar.gz /usr/src/libzbxpgsql.tar.gz

RUN tar xzvf zabbix.tar.gz && \
    cd /usr/src/zabbix-$ZBX_VERSION && \
    grep -rl \"\/zbx fs_discovery.patch | xargs sed -i.orig 's|"/zbx|"/rootfs|g' && \
    patch -p1 < fs_discovery.patch && \
    grep -rl \"\/proc/mounts * | xargs sed -i.orig 's|"/proc/mounts|"/rootfs/proc/1/mounts|g' && \
    grep -rl \"\/proc/net * | xargs sed -i.orig 's|"/proc/net|"/rootfs/proc/1/net|g' && \
    grep -rl \"\/proc * | xargs sed -i.orig 's|"/proc|"/rootfs/proc|g' && \
    grep -rl \"\/dev\/ * | xargs sed -i.orig 's|"/dev/|"/rootfs/dev/|g' && \
    grep -rl \"\/sys * | xargs sed -i.orig 's|"/sys|"/rootfs/sys|g' && \
    ./configure --enable-agent --with-gnutls && \
    make -j && make install && \
    rm -rf /usr/src/zabbix.tar.gz

RUN cd /usr/src/zabbix-$ZBX_VERSION/src/modules/zabbix_module_docker && \
    grep -rl \"\/proc/mounts * | xargs sed -i.orig 's|"/proc/mounts|"/rootfs/proc/1/mounts|g' && \
    make && \
    mkdir -p /usr/local/lib/modules && \
    cp -R /usr/src/zabbix-$ZBX_VERSION/src/modules/zabbix_module_docker/zabbix_module_docker.so /usr/local/lib/modules/zabbix_module_docker.so

RUN tar xzvf libzbxpgsql.tar.gz && \
    cd /usr/src/libzbxpgsql-$LIBZBXPGSQL_VERSION && \
    ./configure --with-zabbix=/usr/src/zabbix-$ZBX_VERSION && \
    make && \
    make install

RUN easy_install pip

RUN pip install ansible boto elasticsearch pymongo zabbix-api

COPY build/ansible.patch /root/ansible.patch

RUN cd /usr/local/lib/python2.7/dist-packages/ansible && patch -p3 < ~/ansible.patch

# Add bash config
COPY build/.bashrc /root/.bashrc

COPY build/etc /etc

COPY build/usr /usr

COPY build/run.sh /run.sh

COPY src/zabbix /zabbix

COPY src/ansible /ansible

RUN chmod +x /run.sh

COPY build/run_zabbix_component.sh /run_zabbix_component.sh

RUN chmod +x /run_zabbix_component.sh

EXPOSE 10050/TCP

ENTRYPOINT ["/run.sh"]
```

**Comment by cavaliercoder** [comment] 2017-05-10 04:28
Huzzah! I have replicated the issue using your Dockerfile. I'll get to work resolving it and will advise.

**Comment by Atem18** [comment] 2017-05-10 08:00
@cavaliercoder Thanks a lot

**Comment by Atem18** [comment] 2017-05-24 09:18
@cavaliercoder Have you got the chance to make it work or make a temporary workaround ?

**Comment by cavaliercoder** [comment] 2017-06-18 11:32
Im no longer able to replicate this issue, even with module v1.1.0, with Zabbix 3.2.5 on your Docker image.

What is the Image ID of your Debian container? I have tried both `8cedef9d7368` (8.7) and `a25c1eed1c6f` (8.8).

**Comment by cavaliercoder** [comment] 2017-06-18 12:26
I think I have an effective way of replicating and working around this issue now. Essentially, the module intends to use the Zabbix sources only for it's headers. When you run `./configure` on the Zabbix sources, these headers are mutated (e.g. adding `config.h`) and things become a little hairy.

For example, in the Zabbix sources, `sysinc.h` asks to include `config.h`. The module also has a `config.h` file and so it's hard to know which one will be compiled.

I was able to repeatedly work around the issue by using the raw Zabbix sources. I.e. don't configure the Zabbix sources before configuring the module.

The best solution would be if Zabbix released a `zabbix-devel` package which only installs platform-configured headers, ready for use by developers. See: https://support.zabbix.com/browse/ZBXNEXT-3157

**Closed** 2017-06-18 12:34 UTC

**Comment by otheus** [comment] 2021-03-16 23:27
I ran into this problem with v1.1.0 and CentOS7 because I installed the sources from src.rpm (in order to stay consistent with the version being used/deployed). The fix in my case was to go to the rpmbuild/SPECS directory and run `rpmbuild -bp zabbix`. I had accidentally started a full build which triggered the problem.

But there is another fix which might be a good idea in general to use. (or not):

Simply redefine `ZBX_CONST_STRING(str)`

```
diff --git a/src/pg_bgwriter.c b/src/pg_bgwriter.c
index d7e0613..911159d 100644
--- a/src/pg_bgwriter.c
+++ b/src/pg_bgwriter.c
@@ -19,6 +19,9 @@

 #include "libzbxpgsql.h"

+/** Redefine macro that is sometimes defined in a way to trigger an error if
+ ** the zabbix sources are not 'pristine' **/
+#define ZBX_CONST_STRING(str) str
 /*
  * Custom keys pg.* (for each field in pg_stat_bgwriter)
  *
```

Build example:  
```
pg_bgwriter.c:24:0: warning: "ZBX_CONST_STRING" redefined [enabled by default]
 #define ZBX_CONST_STRING(str) str
 ^
In file included from /home/c102/c10267/rpmbuild/BUILD/zabbix-3.0.31/include/module.h:23:0,
                 from libzbxpgsql.h:45,
                 from pg_bgwriter.c:20:
/home/c102/c10267/rpmbuild/BUILD/zabbix-3.0.31/include/zbxtypes.h:162:0: note: this is the location of the previous definition
 #define ZBX_CONST_STRING(str) ""str
 ```
 
 The problem is reproducible with the following code:
 ```
 #include <stdio.h>
main() {
  __const char* svar = "This is a constant string";
# define ZBX_CONST_STRING(str) ""str
  printf(ZBX_CONST_STRING(svar));
}
```

I will hazard a guess and say the original def of  `ZBX_CONST_STRING` has something like `(const char*)(str)`
