### ISSUE TITLE
PostgreSQL Backend connections are exhausted on Zabbix server

### ISSUE THREAD

**Issue by huegelc** [cavaliercoder/libzbxpgsql#71] opened 2017-01-25 13:25 UTC
Hi,
I´m running Zabbix Server 3.2.3 with PostgreSQL. After importing the postgresql template I get a issue warning "PostgreSQL Backend connections are exhausted on Zabbix server"
After analyzing the problem I see that the item doesnt collect any data. 

![neos_network_monitoring__nnm___history__refreshed_every_30_sec__](https://cloud.githubusercontent.com/assets/6955465/22292080/e8fcd1fa-e309-11e6-9b30-89cc16504f73.png)

Otherwise the template is working as expected.
Is there any fix for this? Thank you

**Comment by henriavelabarbe** [comment] 2017-01-27 08:14
Hi, I have the same issue on Postgresql 9.6.1, agent zabbix 3.2.0.
It seems the culprit is :
{AHOST:pg.prepared_xacts_ratio[{$PG_CONN},{$PG_DB}].last()}<{$PG_BACKENDS_CRIT}
It seems a ratio is compared to a count.

**Comment by huegelc** [comment] 2017-01-28 08:05
Hiy thx for your reply.
Is there any way to fix this?

**Comment by henriavelabarbe** [comment] 2017-01-30 10:14
Hi,
I'm not the dev, so my answer is my own advice, not official.
After checking more in the source code, it seems the pg_prepared_xacts_ratio is the count of prepared transactions or 0 if the setting is disabled.
Tough I'm not sure what should be really measured given the trigger label.
I think the expression is wrong and should probably be compared to the actual count of transactions.

On my side, I disabled the trigger as it is wrong anyway.

**Comment by huegelc** [comment] 2017-01-30 10:51
Hi,
thanks. Yes, I have disabled the trigger also. Maybe the dev could have a look at the template?! @cavaliercoder

**Comment by cavaliercoder** [comment] 2017-01-30 11:48
Yeah, totally going to fix this shortly, in the next release. Just trying to dig up the logic I was actually trying to apply with this trigger.
I would recommend disabling this trigger for now.

**Comment by kissvoice** [comment] 2017-02-06 20:39
I'm experiencing the same issue as well on 9.6 PostgreSQL and pg.prepared_xacts_ratio stating backends exhausted.  I've noted that pg.backends.count also seems to be off.  Doing a zabbix_get pg.backends.count returns 20.  Not sure if its related at all but I would assume so, due to a ratio requiring a base for calculation.  I'm configured at the default of 100 on connections and have confirmed via psql via `\x ` `select * from pg_settings where name ='max_connections';` that the db is in fact at 100 connections.

`postgres=# select setting from pg_settings where name ='max_connections';
-[ RECORD 1 ]
setting | 100`

When attempting a zabbix_get for pg.prepared_xacts_ratio I'm getting a connection refused however.  Note the port its trying for pg.prepared_xacts_ration 10050.

`root@zabbix:~# zabbix_get -s domain.com -k pg.prepared_xacts_ratio[user=monitoring,db]`
`zabbix_get [12916]: Get value error: cannot connect to [[tbync01b.kissvoice.com]:10050]: [111] Connection refused`
`root@zabbix:~# zabbix_get -s domain.com -k pg.backends.count[user=monitoring,db]`
`20`

Other than that everything is a Rock n Rock!  Appreciate the attention.

**Comment by cavaliercoder** [comment] 2017-02-20 13:13
Fixed in v1.1.0. The trigger has been updated to use the correct key: `pg.backends.free`

**Closed by cavaliercoder** 2017-02-20 13:13 UTC
