### ISSUE TITLE
Failed dependencies with epel agent packages

### ISSUE THREAD

**Issue by jack92025** [cavaliercoder/libzbxpgsql#18] opened 2015-09-30 20:41 UTC
Sorry hated to open an issue but I'm probably not the only user of Centos 7 w/Postgres9.2.  I really liked the premise behind your library but can't break the server.

Is the break because I'm using zabbix22?

[root@tcdb1 ~]# rpm -ivh libzbxpgsql-0.2.1-1.el7.x86_64.rpm
error: Failed dependencies:
        zabbix-agent >= 2.2.0 is needed by libzbxpgsql-0.2.1-1.el7.centos.x86_64
[root@tcdb1 ~]# rpm -qa | grep zabb
zabbix22-2.2.10-1.el7.x86_64
zabbix22-agent-2.2.10-1.el7.x86_64
zabbix-release-2.2-1.el7.noarch

**Comment by cavaliercoder** [comment] 2015-10-01 01:42
Recurrence of #6.

Where are you sourcing the `zabbix22-agent` packages from? If I look at the Zabbix official repos for EL7, the package name is `zabbix-agent`. http://repo.zabbix.com/zabbix/2.2/rhel/7/x86_64/

**Comment by cavaliercoder** [comment] 2015-10-02 07:49
I've found that the `zabbix22-agent` packages are sourced from EPEL and can confirm that the libzbxpgsql packages currently only support the Zabbix official packages. Installation instructions for these packages can be found here: https://www.zabbix.com/documentation/2.2/manual/installation/install_from_packages

I'll experiment with adding support for the EPEL packages (maybe by requiring `/usr/sbin/zabbix_agentd` instead of `zabbix-agent`) and I'll also follow up with Zabbix support to see if they can adjust their packages to indicate that the Zabbix and EPEL package both `Provide` the same virtual package.

**Comment by jack92025** [comment] 2015-10-02 20:07
Yes, epel is the repo I had to source zabbix22 from.  Didn't want to take you from the important work, just wanted to let you know there was a challenge for those of us wanting to try the plugin.  Thanks for looking into it.

**Comment by cavaliercoder** [comment] 2015-10-06 15:47
Very keen to fix this issue for you, as many people use the EPEL packages. I've raised a request with the package maintainers to see what they think. https://bugzilla.redhat.com/show_bug.cgi?id=1269204

**Comment by cavaliercoder** [comment] 2016-04-03 10:13
The issue is currently assigned to @volter in bugzilla. I've poked him in #zabbix so hopefully he will have a moment to take a look.

**Comment by cavaliercoder** [comment] 2016-08-21 03:41
After discussing this in depth on IRC #zabbix, no agreement could be made between Zabbix and EPEL packagers to resolve this issue in a mutually beneficial way. Unfortunately this won't be fixed in the short term.

**Closed by cavaliercoder** 2016-08-21 03:41 UTC
Labels: wontfix
